AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy SNS Notification Topics and Alarms for Generic Account Notification

Parameters:
  pAccountDescription:
    Description: Short Name for account (ie dev,ref,prod)
    Type: String

  pInitialSubscriberEmail:
    Description: Add this initial email to the alerts
    Type: String

  pBillingThreshold:
    Description: Sets the billing alert to go off above this figure
    Type: Number

Resources:
  SNSAlertsCritical:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join ['', ["Critical Alerts for ", !Ref 'pAccountDescription']]
      Subscription:
      - Endpoint: !Ref 'pInitialSubscriberEmail'
        Protocol: email
      TopicName: !Join ['-', ["Critical-Alerts", !Ref 'pAccountDescription']]
  SNSAlertsError:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join ['', ["Error Alerts for ", !Ref 'pAccountDescription']]
      Subscription:
      - Endpoint: !Ref 'pInitialSubscriberEmail'
        Protocol: email
      TopicName: !Join ['-', ["Error-Alerts", !Ref 'pAccountDescription']]
  SNSAlertsInfo:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join ['', ["Info Alerts for ", !Ref 'pAccountDescription']]
      Subscription:
      - Endpoint: !Ref 'pInitialSubscriberEmail'
        Protocol: email
      TopicName: !Join ['-', ["Info-Alerts", !Ref 'pAccountDescription']]

  SNSAlertPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: AlertTopicPolicy
        Version: '2012-10-17'
        Statement:
        - Sid: My-statement-id
          Effect: Allow
          Principal:
            AWS: "*"
            # AWS: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':root']]
          Action: sns:Publish
          Resource: '*'
          Condition:
            StringEquals:
              AWS:SourceOwner: !Ref AWS::AccountId
      Topics: [!Ref 'SNSAlertsCritical', !Ref 'SNSAlertsError', !Ref 'SNSAlertsInfo']

  SpendingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: !Join ['', [Alarm if AWS spending is over $, !Ref 'pBillingThreshold']]
      Namespace: AWS/Billing
      MetricName: EstimatedCharges
      Dimensions:
      - Name: Currency
        Value: USD
      Statistic: Maximum
      Period: '21600'
      EvaluationPeriods: '1'
      Threshold: !Ref 'pBillingThreshold'
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: [!Ref 'SNSAlertsError']

Outputs:
  SNSAlertsCriticalArn:
    Value: !Ref 'SNSAlertsCritical'
    Export:
      Name: SNSAlertsCriticalArn
  SNSAlertsErrorArn:
    Value: !Ref 'SNSAlertsError'
    Export:
      Name: SNSAlertsErrorArn
  SNSAlertsInfoArn:
    Value: !Ref 'SNSAlertsInfo'
    Export:
      Name: SNSAlertsInfoArn
  TemplateVersion:
    Value: "0.1.0"
